//! Chat IPC commands (daemon-backed).
//!
//! Split into focused submodules:
//! - `run`        — per-turn execution: `start_session`, `send_message`,
//!                  `cancel_turn`, `blocks_to_prompt_text`. All turns run in
//!                  the detached daemon via RPC.
//! - `attachments` - image attachments: `paste_image`, `paste_attachment`,
//!                  `paste_attachment_from_path`, shared `validate_session_id`
//!                  + `write_attachment` helpers, and a `pub(crate)`
//!                  `read_attachment` local-disk reader - NOT the Tauri
//!                  command of the same name, see `lifecycle`.
//! - `history`    — read-only transcript replays: `load_history`,
//!                  `load_history_page`, `transcript_stats`, `load_event_detail`.
//! - `daemon_bridge` - daemon `chat_event` -> `chat:<id>` event pump;
//!                  `ensure_session_attached` is its Tauri entry point.
//! - `history_list` — History-view listing pipeline: `list_history`.
//! - `lifecycle`  — AppHandle / process-tree side: `gc_attachments`,
//!                  `takeover_manual`, `detach_window`, `reattach_window`,
//!                  `respond_permission`, `respond_question`, and the
//!                  Tauri `read_attachment` command (session-aware wrapper
//!                  around `attachments::read_attachment`).
//! - `terminal`   — external-terminal spawning: `open_session_in_terminal`,
//!                  `open_terminal_in_directory`.
//!
//! All `#[tauri::command]` items are re-exported here so the parent
//! `ipc.rs` `pub use chat::*;` keeps surfacing the existing
//! `ipc::<command>` shape used by `lib.rs` `invoke_handler!`.

pub mod attachments;
pub mod builtins;
pub mod daemon_bridge;
pub mod history;
pub mod history_list;
pub mod lifecycle;
pub mod run;
pub mod start_retry;
pub mod terminal;
pub mod watcher;

// Glob re-exports so the `__cmd__<name>` symbols generated by
// `#[tauri::command]` are reachable via `crate::ipc::chat::<cmd>` (and via
// the parent `ipc.rs` `pub use chat::*;`). A named `pub use foo::bar`
// re-exports `bar` only; the macro-generated sibling stays hidden - a
// `#[tauri::command]` fn needs the glob form or `generate_handler!` can't
// find its hidden `__cmd__`/`__tauri_command_name_` sibling.
//
// `attachments::read_attachment` is `pub(crate)`, not a `#[tauri::command]`
// (kept at a frozen 1-arg signature because `daemon/methods/registry/
// attachments.rs` calls it directly by that exact path). Both globs below
// bring a `read_attachment` into this module's namespace (that plain fn,
// and `lifecycle`'s real Tauri command), which rustc treats as an
// `ambiguous_glob_imports` future-incompatibility warning rather than
// picking the command - the explicit re-export right after resolves it:
// an explicit import always wins over a glob-imported name.
pub use attachments::*;
pub use builtins::*;
pub use daemon_bridge::*;
pub use history::*;
pub use history_list::*;
pub use lifecycle::*;
pub use lifecycle::read_attachment;
pub use run::*;
pub use terminal::*;
pub use watcher::*;
